version: "3"
services:
  backend:
    build: 
      context: ./Backend
      network: host
    ports:
      - "8100:8100"
  serviceapis:
    build: 
      context: ./Services
      network: host
    ports:
      - "8080:8080"
  askbob:
    build: 
      context: ./AskBob Concierge
      network: host
    ports:
      - "8000:8000"
    links:
      - serviceapis