version: "3.9"
services:
  concierge:
    build: .
    image: concierge
    ports:
      - 8080
      - 8100
  askbob:
    build: 
      context: .
      dockerfile: askbob.Dockerfile
    image: askbob
    ports:
      - 8000
